name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: while sleep 300; do echo "keep-alive"; done &
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
  test-temp:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: while sleep 300; do echo "keep-alive"; done &
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npx vitest run tests/tempbuffer.test.js
  test-sidemenu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: while sleep 300; do echo "keep-alive"; done &
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npx vitest run tests/sidemenu.test.js
